# MAIN CONFIGURATION

app.name = puzzle-desktop
app.uuid = 1d7eaefa-388a-46fb-9dee-7827611006f9
app.version = 1

# APP
app.namespace = app
app.mainForm = helloworld
app.showMainForm = 1

app.fx.splash.autoHide = 1